FROM ubuntu:22.04

# install apt packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    build-essential \
    git \
    gdb \
    && rm -rf /var/lib/apt/lists/*

# create symlink for python (to fix scripts and environments that assume python is python3)
RUN ln -s /usr/bin/python3 /usr/bin/python

# install pip
RUN python -m pip install mkdocs